apiVersion: v1
kind: ConfigMap
metadata:
  name: juridico-config
  namespace: juridico-system
data:
  APP_NAME: "Sistema Jurídico"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://juridico.example.com"
  
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
  
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "juridico_system"
  
  BROADCAST_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  FILESYSTEM_DISK: "s3"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "noreply@juridico.example.com"
  MAIL_FROM_NAME: "Sistema Jurídico"
  
  ELASTICSEARCH_HOSTS: "elasticsearch-service:9200"
  ELASTICSEARCH_INDEX_PREFIX: "juridico"
  
  DOCUMENTS_DISK: "s3"
  DOCUMENTS_PATH: "documents"
  MAX_DOCUMENT_SIZE: "10240"
  
  ENCRYPT_DOCUMENTS: "true"
  
  CACHE_TTL: "3600"
  SEARCH_CACHE_TTL: "1800"
  API_RATE_LIMIT: "60"
  
  BACKUP_ENABLED: "true"
  BACKUP_SCHEDULE: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_DISK: "s3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: juridico-system
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /var/www/public;
        index index.php index.html index.htm;
        
        client_max_body_size 100M;
        
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
        
        location ~ \.php$ {
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        
        location ~ /\.ht {
            deny all;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }