apiVersion: v1
kind: Namespace
metadata:
  name: juridico-system
  labels:
    name: juridico-system
    app: sistema-juridico
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: juridico-quota
  namespace: juridico-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: juridico-limits
  namespace: juridico-system
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim